services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:Rb65g2he5jTvZ+M+H4vQSRfSbXoDG9nmo/jcPmd1SRI=
      - key: APP_NAME
        value: Laravel
      - key: APP_URL
        value: https://doviz-takip.onrender.com/
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d10fprripnbc738pm320-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: doviz_mysql
      - key: DB_USERNAME
        value: doviz_mysql_user
      - key: DB_PASSWORD
        value: H9ui7RHeO7kZhslK4Xxa0bc8sTYrmfYG

databases:
  - name: doviz_mysql
    plan: free
    postgresVersion: 16
